[package]
name = "vers"
version = "1.0.0"
authors = ["The Vers developers"]
edition = "2018"

[workspace]
members = [
    "cli/",
    "compiler/",
]

[dependencies]
cli = { path = "cli/" }
compiler = { path = "compiler/" }
